; Apio project configuration file.
; See https://fpgawars.github.io/apio/docs/project-file for details.

[env:default]
default-testbench = examples/ex1_led_switch/ex1_tb.v
board = pico-ice
top-module = top
